openapi: 3.0.1
info:
  title: Config V1 Bucket Service API
  description: '

    The Config API provides standard HTTP/JSON REST endpoints for creating, reading,

    updating, deleting, and listing configurable Chronosphere resources.


    Use this link to download the raw Swagger specification:

    <a href="/api/v1/config/swagger.json">/api/v1/config/swagger.json</a>

    '
  version: v1
servers:
- url: /
tags:
- name: Service
paths:
  /api/v1/config/services/{slug}:
    get:
      tags:
      - Service
      operationId: ReadService
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configv1ReadServiceResponse'
        '404':
          description: Cannot read the Service because the slug does not exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        '500':
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        default:
          description: An undefined error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
components:
  schemas:
    genericError:
      type: object
      additionalProperties: true
    apiError:
      type: object
      properties:
        code:
          type: integer
          description: An optional private error code whose values are undefined.
          format: int32
        message:
          type: string
          description: An error message describing what went wrong.
    configv1ReadServiceResponse:
      type: object
      properties:
        service:
          $ref: '#/components/schemas/configv1Service'
    configv1Service:
      type: object
      properties:
        slug:
          type: string
          description: Unique identifier of the Service. If a `slug` isn't provided, one will be generated based of the `name` field. You can't modify this field after the Service is created.
        name:
          type: string
          description: Required. Name of the Service. You can modify this value after the Service is created.
        created_at:
          type: string
          description: Timestamp of when the Service was created. Cannot be set by clients.
          format: date-time
          readOnly: true
        updated_at:
          type: string
          description: Timestamp of when the Service was last updated. Cannot be set by clients.
          format: date-time
          readOnly: true
        team_slug:
          type: string
          description: Required slug of the team the service collection belongs to.
        description:
          type: string
          description: Optional description of the service collection.
        notification_policy_slug:
          type: string
          description: 'Slug of the notification policy used by default for monitors in this service collection.

            This is optional if the collection does not contain monitors or all of its monitors explicitly reference a policy.

            This does not override the policy used when a monitor explicitly references a policy.'
x-original-swagger-version: '2.0'
