openapi: 3.2.0
info:
  description: 'WARNING: This API is unstable and is meant for experimentation only. Do not

    use this API in production. The endpoints and schemas referenced in this

    documentation will be changed or removed without notice and without any

    backwards compatibility guarantee. Note that even though this API is unstable,

    it is still connected to production data, so use with caution.'
  title: Config Unstable Trace Top Tag Config API
  version: UNSTABLE
tags:
- name: TraceTopTagConfig
paths:
  /api/unstable/config/trace-top-tag-config:
    delete:
      operationId: DeleteTraceTopTagConfig
      parameters:
      - in: query
        name: dry_run
        schema:
          type: boolean
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configunstableDeleteTraceTopTagConfigResponse'
        '400':
          description: Cannot delete the TraceTopTagConfig because it is in use.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        '404':
          description: Cannot delete the TraceTopTagConfig because the slug does not exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        '500':
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        default:
          description: An undefined error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
      tags:
      - TraceTopTagConfig
      summary: Delete trace top tag config
      x-summary-source: derived
    get:
      operationId: ReadTraceTopTagConfig
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configunstableReadTraceTopTagConfigResponse'
        '404':
          description: Cannot read the TraceTopTagConfig because TraceTopTagConfig has not been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        '500':
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        default:
          description: An undefined error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
      tags:
      - TraceTopTagConfig
      summary: Read trace top tag config
      x-summary-source: derived
    post:
      operationId: CreateTraceTopTagConfig
      responses:
        '200':
          description: A successful response containing the created TraceTopTagConfig.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configunstableCreateTraceTopTagConfigResponse'
        '400':
          description: Cannot create the TraceTopTagConfig because the request is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        '409':
          description: Cannot create the TraceTopTagConfig because there is a conflict with an existing TraceTopTagConfig.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        '500':
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        default:
          description: An undefined error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
      tags:
      - TraceTopTagConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/configunstableCreateTraceTopTagConfigRequest'
        required: true
      summary: Create trace top tag config
      x-summary-source: derived
    put:
      operationId: UpdateTraceTopTagConfig
      responses:
        '200':
          description: A successful response containing the updated TraceTopTagConfig.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configunstableUpdateTraceTopTagConfigResponse'
        '400':
          description: Cannot update the TraceTopTagConfig because the request is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        '404':
          description: Cannot update the TraceTopTagConfig because TraceTopTagConfig has not been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        '500':
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiError'
        default:
          description: An undefined error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
      tags:
      - TraceTopTagConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/configunstableUpdateTraceTopTagConfigRequest'
        required: true
      summary: Update trace top tag config
      x-summary-source: derived
components:
  schemas:
    configunstableUpdateTraceTopTagConfigResponse:
      properties:
        trace_top_tag_config:
          $ref: '#/components/schemas/configunstableTraceTopTagConfig'
      type: object
    configunstableUpdateTraceTopTagConfigRequest:
      properties:
        trace_top_tag_config:
          $ref: '#/components/schemas/configunstableTraceTopTagConfig'
        create_if_missing:
          description: If `true`, the TraceTopTagConfig will be created if it does not already exist. If `false`, an error will be returned if the TraceTopTagConfig does not already exist.
          type: boolean
        dry_run:
          description: If `true`, validates the specified configuration without creating or updating the TraceTopTagConfig. If the specified configuration is valid, the endpoint returns a partial response without the TraceTopTagConfig. If the specified configuration is invalid, the endpoint returns an error.
          type: boolean
      type: object
    configunstableCreateTraceTopTagConfigResponse:
      properties:
        trace_top_tag_config:
          $ref: '#/components/schemas/configunstableTraceTopTagConfig'
      type: object
    genericError:
      additionalProperties: true
      type: object
    configunstableCreateTraceTopTagConfigRequest:
      properties:
        trace_top_tag_config:
          $ref: '#/components/schemas/configunstableTraceTopTagConfig'
        dry_run:
          description: If `true`, validates the specified configuration without creating the TraceTopTagConfig. If the specified configuration is valid, the endpoint returns a partial response without the TraceTopTagConfig. If the specified configuration is invalid, the endpoint returns an error.
          type: boolean
      type: object
    apiError:
      properties:
        code:
          description: An optional private error code whose values are undefined.
          format: int32
          type: integer
        message:
          description: An error message describing what went wrong.
          type: string
      type: object
    TraceTopTagConfigTraceTopTag:
      properties:
        tag_name:
          description: Tag name that uniquely identifies a tag.
          type: string
        description:
          description: Human readable description of the tag.
          type: string
      type: object
    configunstableTraceTopTagConfig:
      description: 'TraceTopTagConfig is a singleton configuration object that specifies the

        configuration for top tracing tags.'
      properties:
        id:
          type: string
        created_at:
          description: Timestamp of when the TraceTopTagConfig was created. Cannot be set by clients.
          format: date-time
          readOnly: true
          type: string
        updated_at:
          description: Timestamp of when the TraceTopTagConfig was last updated. Cannot be set by clients.
          format: date-time
          readOnly: true
          type: string
        source_client:
          type: string
        top_tags:
          description: The list of "top" tags. Must be unique by tag_name.
          items:
            $ref: '#/components/schemas/TraceTopTagConfigTraceTopTag'
          type: array
      type: object
    configunstableReadTraceTopTagConfigResponse:
      properties:
        trace_top_tag_config:
          $ref: '#/components/schemas/configunstableTraceTopTagConfig'
      type: object
    configunstableDeleteTraceTopTagConfigResponse:
      type: object
